In [7]:
print("Hello")

Hello


In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [9]:
print(np.__version__)
print(pd.__version__)
#print()

1.26.3
2.1.4


In [10]:
a=np.array([1,2,3,4,5])
b=np.array([(1,2,3,4.7),(5,6,7,8)])
print(a)
print(b)

[1 2 3 4 5]
[[1.  2.  3.  4.7]
 [5.  6.  7.  8. ]]


In [11]:
print("Shape of the array ",a.shape)
print("Length of the array ",len(a))
print("Dimensions of array ",a.ndim)
print("Data type of a: ",a.dtype)
print("Data type of b: ",b.dtype)

Shape of the array  (5,)
Length of the array  5
Dimensions of array  1
Data type of a:  int64
Data type of b:  float64


In [12]:
c=b.astype(int)
print(c)

[[1 2 3 4]
 [5 6 7 8]]


In [13]:
d=np.array([[(1.5,2,3),(4,5,6)],[(3,2,1),(4,5,6)]])

In [14]:
print("Shape of array d ",d.shape)
print("Length of the array d ",len(d))
print("Dimensions of array ",d.ndim)
print("Data type of d: ",d.dtype)

Shape of array d  (2, 2, 3)
Length of the array d  2
Dimensions of array  3
Data type of d:  float64


In [15]:
t1=np.zeros((3,4))
t2=np.ones((3,4))
f=np.arange(10,25,2)
h=np.linspace(0,2,9)
r=np.random.random((2,3))
e=np.empty((2,2))
i=np.eye(3)
print(r)
print(h)

[[0.18832314 0.59740205 0.28693311]
 [0.3419557  0.21432315 0.52533728]]
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [41]:
np.save("MY_ARRAY.npy",a)

In [17]:
print(a)

[1 2 3 4 5]


In [18]:
print(a.sum())
print(a.min())
print(a.max(axis=0))


15
1
5


In [19]:
print(d)

[[[1.5 2.  3. ]
  [4.  5.  6. ]]

 [[3.  2.  1. ]
  [4.  5.  6. ]]]


In [20]:
print(d.max(axis=0))
print(d.max(axis=1))

[[3. 2. 3.]
 [4. 5. 6.]]
[[4. 5. 6.]
 [4. 5. 6.]]


In [21]:
k=d.ravel()
print(k)

[1.5 2.  3.  4.  5.  6.  3.  2.  1.  4.  5.  6. ]


In [22]:
r=k.reshape(3,4)
print(r)

[[1.5 2.  3.  4. ]
 [5.  6.  3.  2. ]
 [1.  4.  5.  6. ]]


resize
append
insert 
delete dot

In [23]:
r = np.resize(r, (2, 3)) 
print(r)

[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [24]:
import pandas as pd
from pandas import DataFrame

In [25]:
df=DataFrame({
    'Name':['Abc','Pqr','Xyz'],
    'age':[10,20,30]
})

In [26]:
print(df)

  Name  age
0  Abc   10
1  Pqr   20
2  Xyz   30


In [27]:
print(df['Name'])
print(df.age)

0    Abc
1    Pqr
2    Xyz
Name: Name, dtype: object
0    10
1    20
2    30
Name: age, dtype: int64


In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    3 non-null      object
 1   age     3 non-null      int64 
dtypes: int64(1), object(1)
memory usage: 180.0+ bytes


In [29]:
df=pd.read_csv(r"assets/diabetes.csv")


In [30]:
df.shape

(768, 9)

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [32]:
df.head(10)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   
5            5      116             74              0        0  25.6   
6            3       78             50             32       88  31.0   
7           10      115              0              0        0  35.3   
8            2      197             70             45      543  30.5   
9            8      125             96              0        0   0.0   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1  
5                     0.201   30        0  
6                     0.248   26        1  
7                     0.134   29        0  
8                     0.158   53        1  
9                     0.232   54        1

In [33]:
df.head(767)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
762            9       89             62              0        0  22.5   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
762                     0.142   33        0  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  

[767 rows x 9 columns]

In [34]:
df.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [35]:
idx=df.columns
print(idx)

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')


In [36]:
print(df.columns[1])

Glucose


In [37]:
print(df.columns.values)

['Pregnancies' 'Glucose' 'BloodPressure' 'SkinThickness' 'Insulin' 'BMI'
 'DiabetesPedigreeFunction' 'Age' 'Outcome']


In [38]:
X=df.drop('Outcome',axis=1)
print(X)

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  


In [39]:
print(df[['Age','Outcome']])

     Age  Outcome
0     50        1
1     31        0
2     32        1
3     21        0
4     33        1
..   ...      ...
763   63        0
764   27        0
765   30        0
766   47        1
767   23        0

[768 rows x 2 columns]


In [1]:
y=df.Outcome

NameError: name 'df' is not defined